
variables:
    VERSION: latest

stages:
  - build

build:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  script:
    - docker info
    - cd ubuntu
    - docker build --build-arg VERSION=$VERSION -t bsease/astrometry:$VERSION .
    - echo $DOCKER_HUB_TOKEN > token.txt
    - cat token.txt | docker login --username bsease --password-stdin
    - rm token.txt
    - docker push bsease/astrometry:$VERSION
