
variables:
    VERSION: latest

stages:
  - build

build:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  script:
    - docker info
    - cd ubuntu
    - docker build -t bsease/astrometry:$VERSION .
